<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WebTable</name>
   <tag></tag>
   <elementGuidId>a84ba9f9-26cf-4a52-849d-b3a42940b43d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>${Module}</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
